### ISSUE TITLE
Blue Gate Switch Location in Deedlit

### ISSUE THREAD

**Issue by sassyvania** [Lakifume/Ladybug-Randomizer#1]
I rolled a seed where the blue gate lock switch is in that room under that platform that you have to jump on 50 times (or whatever amount it is) at Stage_00_21

Jumping out triggers a cutscene, Deedlit falls back into the room when it triggers, and then just locks up, cut scene cant continue, no input is excepted, have to alt-f4 to get out of it. 

Settings: randomized all except enemy types, logic complexity 2, seed 4390129867

**Comment by Lakifume** [comment]
Hmm... yeah now that you mention it it makes sense this issue happens. I'll see what I can do. Though in your opinion would it be better to make it so that this check is never progression or not ? Cuz I mean jumping 50 times to get the item every run could be annoying for some.

**Comment by sassyvania** [comment]
Honestly, I think I would do it every run because 1) I'm not the type who speed runs randos (though I know a lot of people are) and 2) I'd always be worried i'd be orphaning a better weapon or something down there. 

I know a lot of randomizers have an "enforce junk location" option where you can make sure a check you never want to do has something pointless in there, though I can't think of what that would be in Deedlit. 

Another option could be that the randomizer modifies the platform to only require 5-10 jumps? Not sure how doable that would be, just an idea.
