### ISSUE TITLE
Having a bow is not enough

### ISSUE THREAD

**Issue by SenseiLeRoof** [Lakifume/Ladybug-Randomizer#2]
Gear and rope gates can only be opened with a bow, but you can't use or even _equip_ a bow until you've had the bow tutorial. Yes, even if you buy one first.

So now the bow _tutorial_ is part of progression logic.

**Comment by Lakifume** [comment]
Yes I am aware of that, that's why the first bow pickup is randomized but still in logic. You should be able to find a bow pickup near the start of the seed
