### ISSUE TITLE
ValueError: Invalid literal for int() with base 10: 'p', Touhou Luna Nights

### ISSUE THREAD

**Issue by KyubeyIncub** [Lakifume/Ladybug-Randomizer#3]
When Key Items, Upgrades, Spells, and Require All Keys re checked, I get this error really consistently. It's quite infuriating.

**Comment by KyubeyIncub** [comment]
Actually, as I mess around some, even making one little change or no changes results in this bug.

**Comment by Lakifume** [comment]
Could you post a screenshot of the full error message and traceback ?

**Comment by KyubeyIncub** [comment]
![image](https://github.com/user-attachments/assets/2279f0e0-58dd-4d18-9e0e-d42b740a5860)
![image](https://github.com/user-attachments/assets/6ed6f73c-e45b-409e-9a38-305858a46bfa)

**Comment by Lakifume** [comment]
Alright now can you go into your C:\Users\\[YOUR USER]\AppData\Local\touhou_luna_nights folder and take a screenshot of its content ?

**Comment by KyubeyIncub** [comment]
![image](https://github.com/user-attachments/assets/3b48413a-5352-4144-9240-61e97a5b051c)

**Comment by KyubeyIncub** [comment]
removing the backup saves I had and the other saves fixed it. Huh.
